# Generated by Django 2.2.3 on 2019-07-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('building', 'apartment_no')},
        ),
    ]
