# Generated by Django 2.2.3 on 2019-07-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190704_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='price',
            field=models.IntegerField(verbose_name='Price (₺)'),
        ),
    ]
